In [1]:
import pandas as pd
import json

In [2]:
flight = pd.read_csv('flight_status.csv')

In [5]:
pd.set_option('display.max_rows', 200)

flight[flight.to=='DAD']

      from   to  active
6497   KIX  DAD       0
6585   HND  DAD       0
6697   NRT  DAD       0
6934   CTU  DAD       0
7055   CAN  DAD       0
7155   HGH  DAD       0
7448   PVG  DAD       0
7739   CGO  DAD       0
7820   HKG  DAD       0
7914   MFM  DAD       0
7963   KHH  DAD       0
8074   TPE  DAD       0
8166   PUS  DAD       0
8182   TAE  DAD       0
8309   ICN  DAD       0
8381   MWX  DAD       0
8597   DEL  DAD       0
9060   PNH  DAD       0
9079   REP  DAD       0
9389   KUL  DAD       0
9691   SIN  DAD       0
9830   BKK  DAD       1
9931   DMK  DAD       0
9969   CNX  DAD       0
11064  DOH  DAD       0

In [2]:
airport = pd.read_json('airport.json')

In [3]:
airport

,country,location,name,code
0,Algeria,Adrar,Touat-Cheikh Sidi Mohamed Belkebir Airport,AZR
1,Algeria,Algiers,Houari Boumedienne Airport,ALG
2,Algeria,Annaba,Rabah Bitat Airport,AAE
3,Algeria,Batna,Batna Airport,BLJ
4,Algeria,Bejaia,Soummam Airport,BJA
...,...,...,...,...
1300,Tuvalu,Funafuti,Funafuti International Airport,FUN
1301,Vanuatu,Luganville,Santo-Pekoa International Airport,SON
1302,Vanuatu,Port Vila,Bauerfield International Airport,VLI
1303,Wallis and Futuna Islands,Futuna,Pointe Vele Airport,FUT
1304,Wallis and Futuna Islands,Wallis,Hihifo Airport,WLS

In [4]:
airport[airport.code=='CDG']

     country location                       name code
837  Belgium    Paris  Charles de Gaulle Airport  CDG

In [6]:
pd.set_option('display.max_rows', 200)

df = pd.read_csv('flight_status_merged.csv')

In [5]:
df

,from,to,active,date,country_from,city_from,name_from,country_to,city_to,name_to
0,HEA,MHD,0,2020-04-06,Afghanistan,Herat,Herat,Iran,Mashad,Mashad
1,HEA,DEL,0,2020-04-06,Afghanistan,Herat,Herat,India,New Delhi,Indira Gandhi Intl
2,JAA,FRU,0,2020-04-06,Afghanistan,Jalalabad,Jalalabad,Kyrgyz Republic,Bishkek,Manas
3,KBL,IST,0,2020-04-06,Afghanistan,Kabul,Khwaja Rawash,Turkey,Istanbul,Ataturk
4,KBL,DEL,0,2020-04-06,Afghanistan,Kabul,Khwaja Rawash,India,New Delhi,Indira Gandhi Intl
...,...,...,...,...,...,...,...,...,...,...
26964,VFA,GBE,0,2020-04-06,Zimbabwe,Victoria Falls,Victoria Falls,Botswana,Gaborone,Sir Seretse Khama International
26965,VFA,JNB,0,2020-04-06,Zimbabwe,Victoria Falls,Victoria Falls,NaN,NaN,NaN
26966,VFA,WDH,0,2020-04-06,Zimbabwe,Victoria Falls,Victoria Falls,NaN,NaN,NaN
26967,VFA,MQP,0,2020-04-06,Zimbabwe,Victoria Falls,Victoria Falls,South Africa,Nelspruit,Kruger Mpumalanga
26968,VFA,NBO,0,2020-04-06,Zimbabwe,Victoria Falls,Victoria Falls,Kenya,Nairobi,Jomo Kenyatta International

In [69]:
df = df.drop(columns=['country', 'cum_case'])

In [10]:
df[~(df['country_from']== df['country_to'])]

In [8]:
pd.set_option('display.max_rows', 200)

df[df.country_to.isnull() & df.active==1]

,from,to,active,date,country_from,city_from,name_from,country_to,city_to,name_to
436,BNE,LAX,1,2020-04-06,Australia,Brisbane,Brisbane International,NaN,NaN,NaN
466,MEL,CGK,1,2020-04-07,Australia,Melbourne,Tullamarine International,NaN,NaN,NaN
539,SYD,SFO,1,2020-04-07,Australia,Sydney,Kingsford Smith,NaN,NaN,NaN
542,SYD,CGK,1,2020-04-08,Australia,Sydney,Kingsford Smith,NaN,NaN,NaN
973,BIM,FLL,1,2020-04-06,Bahamas,Bimini,International,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
26589,STX,MIA,1,2020-04-06,United States Virgin Islands,St Croix Island,Alex Hamilton,NaN,NaN,NaN
26591,STX,FLL,1,2020-04-06,United States Virgin Islands,St Croix Island,Alex Hamilton,NaN,NaN,NaN
26932,LUN,JNB,1,2020-04-06,Zambia,Lusaka,Lusaka,NaN,NaN,NaN
26952,BUQ,JNB,1,2020-04-06,Zimbabwe,Bulawayo,Bulawayo,NaN,NaN,NaN
26958,HRE,JNB,1,2020-04-06,Zimbabwe,Harare,Harare,NaN,NaN,NaN

In [41]:
df[(df['country_from'] == 'Romania') & (df['country_to']== 'Italy') & (df['active'] == 1)]

Empty DataFrame
Columns: [from, to, active, country_from, location_from, name_from, country_to, location_to, name_to]
Index: []

In [42]:
df[(df['country_from'] == 'Italy') & (df['country_to']== 'Romania') & (df['active'] == 1)]

,from,to,active,country_from,location_from,name_from,country_to,location_to,name_to
20981,BLQ,IAS,1,Italy,Bologna,Bologna Airport,Romania,Iași,Iași International Airport

In [40]:
df = df.drop(index=23373)

In [70]:
cases = pd.read_csv('../../data/country.csv')

In [71]:
cases = cases[cases.date == '2020-04-01']
cases

,date,country,lat,long,cum_case,new_case,cum_death,new_death,cum_cured,new_cured,continent,index
5242,2020-04-01,Afghanistan,33.000000,65.000000,237,63.0,4.0,0.0,5.0,0.0,Asia,86
5243,2020-04-01,Albania,41.153300,20.168300,259,16.0,15.0,0.0,67.0,15.0,Europe,85
5244,2020-04-01,Algeria,28.033900,1.659600,847,131.0,58.0,14.0,61.0,15.0,Africa,52
5245,2020-04-01,Andorra,42.506300,1.521800,390,14.0,14.0,2.0,10.0,0.0,Europe,74
5246,2020-04-01,Angola,-11.202700,17.873900,8,1.0,2.0,0.0,1.0,0.0,Africa,158
5247,2020-04-01,Antigua and Barbuda,17.060800,-61.796400,7,0.0,0.0,0.0,0.0,0.0,America,161
5248,2020-04-01,Argentina,-38.416100,-63.616700,1054,0.0,28.0,1.0,248.0,8.0,America,49
5249,2020-04-01,Armenia,40.069100,45.038200,571,39.0,4.0,1.0,31.0,1.0,Asia,64
5250,2020-04-01,Australia,-255.969500,1129.862300,4862,303.0,20.0,2.0,422.0,64.0,Oceania,21
5251,2020-04-01,Austria,47.516200,14.550100,10711,531.0,146.0,18.0,1436.0,341.0,Europe,13
5252,2020-04-01,Azerbaijan,40.143100,47.576900,359,61.0,5.0,0.0,26.0,0.0,Asia,77
5253,2020-04-01,Bahamas,25.034300,-77.396300,21,7.0,1.0,1.0,1.0,0.0,America,132
5254,2020-04-01,Bahrain,26.027500,50.550000,569,2.0,4.0,0.0,337.0,42.0,Asia,65
5255,2020-04-01,Bangladesh,23.685000,90.356300,54,3.0,6.0,1.0,25.0,0.0,Asia,120
5256,2020-04-01,Barbados,13.193900,-59.543200,34,0.0,0.0,0.0,0.0,0.0,America,126
5257,2020-04-01,Belarus,53.709800,27.953400,163,11.0,2.0,1.0,53.0,6.0,Europe,99
5258,2020-04-01,Belgium,50.833300,4.000000,13964,1189.0,828.0,123.0,2132.0,436.0,Europe,11
5259,2020-04-01,Belize,13.193900,-59.543200,3,0.0,0.0,0.0,0.0,0.0,America,175
5260,2020-04-01,Benin,9.307700,2.315800,13,4.0,0.0,0.0,1.0,0.0,Africa,145
5261,2020-04-01,Bhutan,27.514200,90.433600,4,0.0,0.0,0.0,0.0,0.0,Asia,173
5262,2020-04-01,Bolivia,-16.290200,-63.588700,115,8.0,7.0,1.0,1.0,1.0,America,108
5263,2020-04-01,Bosnia and Herzegovina,43.915900,17.679100,459,39.0,13.0,0.0,19.0,2.0,Europe,68
5264,2020-04-01,Botswana,-22.328500,24.684900,4,0.0,1.0,0.0,0.0,0.0,Africa,174
5265,2020-04-01,Brazil,-14.235000,-51.925300,6836,1119.0,240.0,39.0,127.0,0.0,America,17
5266,2020-04-01,Brunei Darussalam,4.535300,114.727700,131,2.0,1.0,0.0,52.0,7.0,Asia,104
5267,2020-04-01,Bulgaria,42.733900,25.485800,422,23.0,10.0,2.0,20.0,3.0,Europe,72
5268,2020-04-01,Burkina Faso,12.238300,-1.561600,282,21.0,16.0,2.0,46.0,14.0,Africa,83
5269,2020-04-01,Myanmar,21.916200,95.956000,15,0.0,1.0,0.0,0.0,0.0,Asia,141
5270,2020-04-01,Burundi,-3.373100,29.918900,2,0.0,0.0,0.0,0.0,0.0,Africa,178
5271,2020-04-01,Cabo Verde,16.538800,-23.041800,6,0.0,1.0,0.0,0.0,0.0,Africa,167
5272,2020-04-01,Cambodia,11.550000,104.916700,109,0.0,0.0,0.0,25.0,2.0,Asia,111
5273,2020-04-01,Cameroon,3.848000,11.502100,233,40.0,6.0,0.0,10.0,5.0,Africa,88
5274,2020-04-01,Canada,671.760700,-1237.628900,9560,1033.0,108.0,8.0,0.0,0.0,America,15
5275,2020-04-01,Central African Republic,6.611100,20.939400,3,0.0,0.0,0.0,0.0,0.0,Africa,176
5276,2020-04-01,Chad,15.454200,18.732200,7,0.0,0.0,0.0,0.0,0.0,Africa,162
5277,2020-04-01,Chile,-35.675100,-71.543000,3031,293.0,16.0,4.0,234.0,78.0,America,25
5278,2020-04-01,China,1083.336700,3684.419700,82361,82.0,3316.0,7.0,76405.0,199.0,Asia,4
5279,2020-04-01,Colombia,4.570900,-74.297300,1065,159.0,17.0,1.0,39.0,8.0,America,47
5280,2020-04-01,Congo Republic,-4.038300,21.758700,19,0.0,0.0,0.0,0.0,0.0,Africa,136
5281,2020-04-01,DR Congo,-4.038300,21.758700,109,11.0,9.0,1.0,3.0,1.0,Africa,110
5282,2020-04-01,Costa Rica,9.748900,-83.753400,375,28.0,2.0,0.0,4.0,0.0,America,76
5283,2020-04-01,Cote d'Ivoire,7.540000,-5.547100,190,11.0,1.0,0.0,9.0,2.0,Africa,94
5284,2020-04-01,Croatia,45.100000,15.200000,963,96.0,6.0,0.0,73.0,6.0,Europe,51
5285,2020-04-01,Cuba,22.000000,-80.000000,212,26.0,6.0,0.0,12.0,4.0,America,90
5286,2020-04-01,Cyprus,35.126400,33.429900,320,58.0,9.0,1.0,28.0,5.0,Asia,81
5287,2020-04-01,Czech Republic,49.817500,15.473000,3508,200.0,39.0,8.0,61.0,16.0,Europe,22
5288,2020-04-01,Denmark,118.156500,2.590000,3280,251.0,104.0,14.0,969.0,894.0,Europe,24
5289,2020-04-01,Diamond Princess,0.000000,0.000000,712,0.0,11.0,1.0,603.0,0.0,not found,60
5290,2020-04-01,Djibouti,11.825100,42.590300,33,3.0,0.0,0.0,0.0,0.0,Africa,127
5291,2020-04-01,Dominica,15.415000,-61.371000,12,0.0,0.0,0.0,0.0,0.0,America,146
5292,2020-04-01,Dominican Republic,18.735700,-70.162700,1284,175.0,57.0,6.0,9.0,4.0,America,43
5293,2020-04-01,Ecuador,-1.831200,-78.183400,2748,508.0,93.0,18.0,58.0,4.0,America,28
5294,2020-04-01,Egypt,26.000000,30.000000,779,69.0,52.0,6.0,179.0,22.0,Africa,57
5295,2020-04-01,El Salvador,13.794200,-88.896500,32,0.0,1.0,0.0,0.0,0.0,America,128
5296,2020-04-01,Equatorial Guinea,1.500000,10.000000,15,3.0,0.0,0.0,1.0,0.0,Africa,140
5297,2020-04-01,Eritrea,15.179400,39.782300,15,0.0,0.0,0.0,0.0,0.0,Africa,139
5298,2020-04-01,Estonia,58.595300,25.013600,779,34.0,5.0,1.0,33.0,7.0,Europe,58
5299,2020-04-01,Eswatini,-26.522500,31.465900,9,0.0,0.0,0.0,0.0,0.0,Africa,157
5300,2020-04-01,Ethiopia,9.145000,40.489700,29,3.0,0.0,0.0,2.0,0.0,Africa,131
5301,2020-04-01,Fiji,-17.713400,178.065000,5,0.0,0.0,0.0,0.0,0.0,Oceania,168
5302,2020-04-01,Finland,64.000000,26.000000,1446,28.0,17.0,0.0,10.0,0.0,Europe,39
5303,2020-04-01,France,44.477200,116.035100,57749,4922.0,4043.0,511.0,11053.0,1540.0,Europe,6
5304,2020-04-01,Gabon,-0.803700,11.609400,18,2.0,1.0,0.0,0.0,0.0,Africa,137
5305,2020-04-01,Gambia,13.443200,-15.310100,4,0.0,1.0,0.0,2.0,2.0,Africa,172
5306,2020-04-01,Georgia,42.315400,43.356900,117,7.0,0.0,0.0,23.0,2.0,Asia,107
5307,2020-04-01,Germany,51.000000,9.000000,77872,6064.0,920.0,145.0,18700.0,2600.0,Europe,5
5308,2020-04-01,Ghana,7.946500,-1.023200,195,34.0,5.0,0.0,31.0,0.0,Africa,92
5309,2020-04-01,Greece,39.074200,21.824300,1415,101.0,50.0,1.0,52.0,0.0,Europe,40
5310,2020-04-01,Greenland,71.706900,-42.604300,10,0.0,0.0,0.0,2.0,0.0,America,150
5311,2020-04-01,Grenada,12.116500,-61.679000,9,0.0,0.0,0.0,0.0,0.0,America,155
5312,2020-04-01,Guatemala,15.783500,-90.230800,39,1.0,1.0,0.0,12.0,0.0,America,123
5313,2020-04-01,Guinea,9.945600,-9.696600,30,8.0,0.0,0.0,0.0,0.0,Africa,130
5314,2020-04-01,Guinea-Bissau,11.803700,-15.180400,9,1.0,0.0,0.0,0.0,0.0,Africa,154
5315,2020-04-01,Guyana,5.000000,-58.750000,19,7.0,2.0,0.0,0.0,0.0,America,134
5316,2020-04-01,Haiti,18.971200,-72.285200,16,1.0,0.0,0.0,1.0,0.0,America,138
5317,2020-04-01,Vatican,41.902900,12.453400,6,0.0,0.0,0.0,0.0,0.0,Europe,165
5318,2020-04-01,Honduras,15.200000,-86.241900,172,31.0,10.0,3.0,3.0,0.0,America,98
5319,2020-04-01,Hungary,47.162500,19.503300,525,33.0,20.0,4.0,40.0,3.0,Europe,66
5320,2020-04-01,Iceland,64.963100,-19.020800,1220,85.0,2.0,0.0,225.0,27.0,Europe,44
5321,2020-04-01,India,21.000000,78.000000,1998,601.0,58.0,23.0,148.0,25.0,Asia,35
5322,2020-04-01,Indonesia,-0.789300,113.921300,1677,149.0,157.0,21.0,103.0,22.0,Asia,38
5323,2020-04-01,Iran,32.000000,53.000000,47593,2988.0,3036.0,138.0,15473.0,817.0,Asia,7
5324,2020-04-01,Iraq,33.000000,44.000000,728,34.0,52.0,2.0,182.0,12.0,Asia,59
5325,2020-04-01,Ireland,53.142400,-7.692100,3447,212.0,85.0,14.0,5.0,0.0,Europe,23
5326,2020-04-01,Israel,31.000000,35.000000,6092,734.0,26.0,6.0,241.0,17.0,Asia,18
5327,2020-04-01,Italy,43.000000,12.000000,110574,4782.0,13155.0,727.0,16847.0,1118.0,Europe,2
5328,2020-04-01,Jamaica,18.109600,-77.297500,44,8.0,3.0,2.0,2.0,0.0,America,121
5329,2020-04-01,Japan,36.000000,138.000000,2178,225.0,57.0,1.0,472.0,48.0,Asia,33
5330,2020-04-01,Jordan,31.240000,36.510000,278,4.0,5.0,0.0,36.0,6.0,Asia,84
5331,2020-04-01,Kazakhstan,48.019600,66.923700,380,37.0,3.0,1.0,26.0,2.0,Asia,75
5332,2020-04-01,Kenya,-0.023600,37.906200,81,22.0,1.0,0.0,3.0,2.0,Africa,114
5333,2020-04-01,South Korea,36.000000,128.000000,9887,101.0,165.0,3.0,5567.0,159.0,Asia,14
5334,2020-04-01,Kosovo,42.602636,20.902977,125,13.0,1.0,0.0,10.0,4.0,Europe,105
5335,2020-04-01,Kuwait,29.500000,47.750000,317,28.0,0.0,0.0,80.0,7.0,Asia,82
5336,2020-04-01,Kyrgyz Republic,41.204400,74.766100,111,4.0,0.0,0.0,3.0,0.0,Asia,109
5337,2020-04-01,Laos,19.856270,102.495496,10,1.0,0.0,0.0,0.0,0.0,Asia,149
5338,2020-04-01,Latvia,56.879600,24.603200,446,48.0,0.0,0.0,1.0,0.0,Europe,69
5339,2020-04-01,Lebanon,33.854700,35.862300,479,9.0,14.0,2.0,43.0,6.0,Asia,67
5340,2020-04-01,Liberia,6.428100,-9.429500,6,3.0,0.0,0.0,0.0,0.0,Africa,166
5341,2020-04-01,Libya,26.335100,17.228331,10,0.0,0.0,0.0,0.0,0.0,Africa,148
5342,2020-04-01,Liechtenstein,47.140000,9.550000,68,0.0,0.0,0.0,0.0,0.0,Europe,117
5343,2020-04-01,Lithuania,55.169400,23.881300,581,44.0,8.0,0.0,7.0,0.0,Europe,63
5344,2020-04-01,Luxembourg,49.815300,6.129600,2319,141.0,29.0,6.0,80.0,0.0,Europe,31
5345,2020-04-01,MS Zaandam,0.000000,0.000000,9,7.0,2.0,2.0,0.0,0.0,not found,156
5346,2020-04-01,Madagascar,-18.766900,46.869100,57,0.0,0.0,0.0,0.0,0.0,Africa,118
5347,2020-04-01,Malaysia,2.500000,112.500000,2908,142.0,45.0,2.0,645.0,108.0,Asia,26
5348,2020-04-01,Maldives,3.202800,73.220700,19,1.0,0.0,0.0,13.0,0.0,Asia,135
5349,2020-04-01,Mali,17.570692,-3.996166,31,3.0,3.0,1.0,0.0,0.0,Africa,129
5350,2020-04-01,Malta,35.937500,14.375400,188,19.0,0.0,0.0,2.0,0.0,Europe,95
5351,2020-04-01,Mauritania,21.007900,10.940800,6,0.0,1.0,0.0,2.0,0.0,Africa,164
5352,2020-04-01,Mauritius,-20.200000,57.500000,161,18.0,6.0,1.0,0.0,0.0,Africa,100
5353,2020-04-01,Mexico,23.634500,-102.552800,1215,121.0,29.0,1.0,35.0,0.0,America,45
5354,2020-04-01,Moldova,47.411600,28.369900,423,70.0,5.0,1.0,23.0,5.0,Europe,70
5355,2020-04-01,Monaco,43.733300,7.416700,55,3.0,1.0,0.0,2.0,0.0,Europe,119
5356,2020-04-01,Mongolia,46.862500,103.846700,14,2.0,0.0,0.0,2.0,0.0,Asia,143
5357,2020-04-01,Montenegro,42.500000,19.300000,123,14.0,2.0,0.0,0.0,0.0,Europe,106
5358,2020-04-01,Morocco,31.791700,-7.092600,654,37.0,39.0,3.0,29.0,5.0,Africa,62
5359,2020-04-01,Mozambique,-18.665695,35.529562,10,2.0,0.0,0.0,0.0,0.0,Africa,147
5360,2020-04-01,Namibia,-22.957600,18.490400,14,3.0,0.0,0.0,2.0,0.0,Africa,142
5361,2020-04-01,Nepal,28.166700,84.250000,5,0.0,0.0,0.0,1.0,0.0,Asia,169
5362,2020-04-01,Netherlands,94.863300,-196.789300,13696,1029.0,1175.0,135.0,260.0,7.0,Europe,12
5363,2020-04-01,New Zealand,-40.900600,174.886000,708,61.0,1.0,0.0,83.0,9.0,Oceania,61
5364,2020-04-01,Nicaragua,12.865400,-85.207200,5,0.0,1.0,0.0,0.0,0.0,America,170
5365,2020-04-01,Niger,17.607800,8.081700,74,47.0,5.0,2.0,0.0,0.0,Africa,115
5366,2020-04-01,Nigeria,9.082000,8.675300,174,39.0,2.0,0.0,9.0,1.0,Africa,97
5367,2020-04-01,Macedonia,41.608600,21.745300,354,25.0,11.0,2.0,17.0,5.0,Europe,78
5368,2020-04-01,Norway,60.472000,8.468900,4863,222.0,44.0,5.0,13.0,0.0,Europe,20
5369,2020-04-01,Oman,21.000000,57.000000,210,18.0,1.0,0.0,34.0,0.0,Asia,91
5370,2020-04-01,Pakistan,30.375300,69.345100,2118,180.0,27.0,1.0,94.0,18.0,Asia,34
5371,2020-04-01,Panama,8.538000,-80.782100,1181,0.0,30.0,0.0,9.0,0.0,America,46
5372,2020-04-01,Papua New Guinea,-6.315000,143.955500,1,0.0,0.0,0.0,0.0,0.0,Oceania,181
5373,2020-04-01,Paraguay,-23.442500,-58.443800,69,4.0,3.0,0.0,1.0,0.0,America,116
5374,2020-04-01,Peru,-9.190000,-75.015200,1323,258.0,38.0,8.0,394.0,0.0,America,42
5375,2020-04-01,Philippines,13.000000,122.000000,2311,227.0,96.0,8.0,50.0,1.0,Asia,32
5376,2020-04-01,Poland,51.919400,19.145100,2554,243.0,43.0,10.0,47.0,40.0,Europe,29
5377,2020-04-01,Portugal,39.399900,-8.224500,8251,808.0,187.0,27.0,43.0,0.0,Europe,16
5378,2020-04-01,Qatar,25.354800,51.183900,835,54.0,2.0,0.0,71.0,9.0,Asia,54
5379,2020-04-01,Romania,45.943200,24.966800,2460,215.0,92.0,10.0,252.0,32.0,Europe,30
5380,2020-04-01,Russia,60.000000,90.000000,2777,440.0,24.0,7.0,190.0,69.0,Europe,27
5381,2020-04-01,Rwanda,-1.940300,29.873900,82,7.0,0.0,0.0,0.0,0.0,Africa,113
5382,2020-04-01,St. Kitts and Nevis,17.357822,-62.782998,8,0.0,0.0,0.0,0.0,0.0,America,160
5383,2020-04-01,St. Lucia,13.909400,-60.978900,13,0.0,0.0,0.0,1.0,0.0,America,144
5384,2020-04-01,St. Vincent and the Grenadines,12.984300,-61.287200,1,0.0,0.0,0.0,1.0,0.0,America,180
5385,2020-04-01,San Marino,43.942400,12.457800,236,0.0,26.0,0.0,13.0,0.0,Europe,87
5386,2020-04-01,Saudi Arabia,24.000000,45.000000,1720,157.0,16.0,6.0,264.0,99.0,Asia,37
5387,2020-04-01,Senegal,14.497400,-14.452400,190,15.0,1.0,1.0,45.0,5.0,Africa,93
5388,2020-04-01,Serbia,44.016500,21.005900,1060,160.0,28.0,12.0,0.0,0.0,Europe,48
5389,2020-04-01,Seychelles,-4.679600,55.492000,10,0.0,0.0,0.0,0.0,0.0,Africa,151
5390,2020-04-01,Sierra Leone,8.460555,-11.779889,2,1.0,0.0,0.0,0.0,0.0,Africa,177
5391,2020-04-01,Singapore,1.283300,103.833300,1000,74.0,3.0,0.0,245.0,5.0,Asia,50
5392,2020-04-01,Slovakia,48.669000,19.699000,400,37.0,1.0,0.0,3.0,0.0,Europe,73
5393,2020-04-01,Slovenia,46.151200,14.995500,841,39.0,15.0,0.0,10.0,0.0,Europe,53
5394,2020-04-01,Somalia,5.152100,46.199600,5,0.0,0.0,0.0,1.0,0.0,Africa,171
5395,2020-04-01,South Africa,-30.559500,22.937500,1380,27.0,5.0,0.0,50.0,19.0,Africa,41
5396,2020-04-01,Spain,40.000000,-4.000000,104118,8195.0,9387.0,923.0,22647.0,3388.0,Europe,3
5397,2020-04-01,Sri Lanka,7.000000,81.000000,146,3.0,3.0,1.0,21.0,4.0,Asia,101
5398,2020-04-01,Sudan,12.862800,30.217600,7,0.0,2.0,0.0,2.0,1.0,Africa,163
5399,2020-04-01,Suriname,3.919300,-56.027800,10,1.0,0.0,0.0,0.0,0.0,America,153
5400,2020-04-01,Sweden,63.000000,16.000000,4947,512.0,239.0,59.0,103.0,87.0,Europe,19
5401,2020-04-01,Switzerland,46.818200,8.227500,17768,1163.0,488.0,55.0,2967.0,1144.0,Europe,9
5402,2020-04-01,Syria,34.802075,38.996815,10,0.0,2.0,0.0,0.0,0.0,Asia,152
5403,2020-04-01,Taiwan,23.700000,121.000000,329,7.0,5.0,0.0,39.0,0.0,Asia,80
5404,2020-04-01,Tanzania,-6.369000,34.888800,20,1.0,1.0,0.0,1.0,0.0,Africa,133
5405,2020-04-01,Thailand,15.000000,101.000000,1771,120.0,12.0,2.0,505.0,163.0,Asia,36
5406,2020-04-01,Timor-Leste,-8.874217,125.727539,1,0.0,0.0,0.0,0.0,0.0,Asia,179
5407,2020-04-01,Togo,8.619500,0.824800,36,2.0,2.0,1.0,10.0,0.0,Africa,124
5408,2020-04-01,Trinidad and Tobago,10.691800,-61.222500,90,3.0,5.0,2.0,1.0,0.0,America,112
5409,2020-04-01,Tunisia,34.000000,9.000000,423,29.0,12.0,2.0,5.0,2.0,Africa,71
5410,2020-04-01,Turkey,38.963700,35.243300,15679,2148.0,277.0,63.0,333.0,90.0,Asia,10
5411,2020-04-01,United States,37.090200,-95.712900,213372,25200.0,4757.0,884.0,8474.0,1450.0,America,1
5412,2020-04-01,Uganda,1.000000,32.000000,44,0.0,0.0,0.0,0.0,0.0,Africa,122
5413,2020-04-01,Ukraine,48.379400,31.165600,794,149.0,20.0,3.0,13.0,3.0,Europe,56
5414,2020-04-01,United Arab Emirates,24.000000,54.000000,814,150.0,8.0,2.0,61.0,0.0,Asia,55
5415,2020-04-01,United Kingdom,321.826200,-423.401100,29865,4384.0,2357.0,564.0,179.0,0.0,Europe,8
5416,2020-04-01,Uruguay,-32.522800,-55.765800,338,0.0,2.0,1.0,41.0,0.0,America,79
5417,2020-04-01,Uzbekistan,41.377500,64.585300,181,9.0,2.0,0.0,12.0,5.0,Asia,96
5418,2020-04-01,Venezuela,6.423800,-66.589700,143,8.0,3.0,0.0,41.0,2.0,America,102
5419,2020-04-01,Vietnam,16.000000,108.000000,218,6.0,0.0,0.0,63.0,5.0,Asia,89
5420,2020-04-01,Palestine,31.952200,35.233200,134,15.0,1.0,0.0,18.0,0.0,Asia,103
5421,2020-04-01,Zambia,-15.416700,28.283300,36,1.0,0.0,0.0,0.0,0.0,Africa,125
5422,2020-04-01,Zimbabwe,-20.000000,30.000000,8,0.0,1.0,0.0,0.0,0.0,Africa,159

In [72]:
df2 = pd.merge(df, cases[['country', 'cum_case']], how='left', left_on='country_from', right_on='country')

In [74]:
df2 = df2.drop(columns=['country'])

In [75]:
df2.to_csv('flight_status_merged.csv', index=False)

In [27]:
fr = pd.read_json('flight_radar.json')

In [31]:
fr[fr['active']==1]

      from   to  active
0      ALG  MZW       1
1      ALG  VIE       1
2      ALG  BRU       1
3      ALG  CRL       1
4      ALG  OUA       1
...    ...  ...     ...
28416  VLI  NOU       1
28417  VLI  AKL       1
28418  VLI  HIR       1
28421  WLS  NOU       1
28422  WLS  FUT       1

[15465 rows x 3 columns]

In [22]:
x = pd.read_csv('test.csv')

ParserError: Error tokenizing data. C error: Expected 2 fields in line 121, saw 3

In [4]:
with open('destination.json', 'r') as file:
    routes = json.load(file)

In [9]:
len(list(routes.keys()))

6010